export const SIGNUP_USER = 'SIGNUP_USER';
export const IS_LOADING = 'IS_LOADING';
export const IS_COMPLETE = 'IS_COMPLETE';
export const USER_ERROR = 'USER_ERROR';
export const NETWORK_ERROR = 'NETWORK_ERROR';

export const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const PASSWORD_RESET_REQUEST_SUCCESSFUL = 'PASSWORD_RESET_REQUEST_SUCCESSFUL';
export const PASSWORD_RESET_REQUEST_FAILED = 'PASSWORD_RESET_REQUEST_FAILED';

export const PASSWORD_RESET_SUCCESSFUL = 'PASSWORD_RESET_SUCCESSFUL';
export const PASSWORD_RESET_FAILED = 'PASSWORD_RESET_FAILED';

export const PASSWORD_RESET_LINK_VALID = 'PASSWORD_RESET_LINK_VALID';
export const PASSWORD_RESET_LINK_INVALID = 'PASSWORD_RESET_LINK_INVALID';

export const VALIDATION_ERROR = 'VALIDATION_ERROR';
