export const IS_LOADING = 'IS_LOADING';
export const IS_COMPLETE = 'IS_COMPLETE';
export const USER_ERROR = 'USER_ERROR';
export const NETWORK_ERROR = 'NETWORK_ERROR';

export const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const SIGNUP_SUCCESSFUL = 'SIGNUP_SUCCESSFUL';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';

export const PASSWORD_RESET_REQUEST_SUCCESSFUL = 'PASSWORD_RESET_REQUEST_SUCCESSFUL';
export const PASSWORD_RESET_REQUEST_FAILED = 'PASSWORD_RESET_REQUEST_FAILED';

export const PASSWORD_RESET_SUCCESSFUL = 'PASSWORD_RESET_SUCCESSFUL';
export const PASSWORD_RESET_FAILED = 'PASSWORD_RESET_FAILED';

export const PASSWORD_RESET_LINK_VALID = 'PASSWORD_RESET_LINK_VALID';
export const PASSWORD_RESET_LINK_INVALID = 'PASSWORD_RESET_LINK_INVALID';

export const VALIDATION_ERROR = 'VALIDATION_ERROR';
export const CLEAR_VALIDATION_ERROR = 'CLEAR_VALIDATION_ERROR';

export const PROFILE_VIEW = 'PROFILE_VIEW';
export const PROFILE_UPDATE = 'PROFILE_UPDATE';
export const PROFILE_UPDATE_USER_IMAGE = 'PROFILE_UPDATE_USER_IMAGE';

export const CLEAR_ERROR = 'CLEAR_ERROR';

export const USER_LOGOUT = 'USER_LOGOUT';

export const SINGLE_ARTICLE_FETCH_SUCCESSFUL = 'SINGLE_ARTICLE_FETCH_SUCCESSFUL';
export const SINGLE_ARTICLE_FETCH_FAILED = 'SINGLE_ARTICLE_FETCH_FAILED';

export const ALL_ARTICLES_FETCH_SUCCESSFUL = 'ALL_ARTICLES_FETCH_SUCCESSFUL';
export const ALL_ARTICLES_FETCH_FAILED = 'ALL_ARTICLES_FETCH_FAILED';

export const CREATE_ARTICLE_SUCESSFUL = 'CREATE_ARTICLE_SUCESSFUL';
export const CREATE_ARTICLE_FAILED = 'CREATE_ARTICLE_FAILED';

export const UPDATE_ARTICLE_SUCESSFUL = 'UPDATE_ARTICLE_SUCESSFUL';
export const UPDATE_ARTICLE_FAILED = 'UPDATE_ARTICLE_FAILED';

export const DELETE_ARTICLE_SUCESSFUL = 'DELETE_ARTICLE_SUCESSFUL';
export const DELETE_ARTICLE_FAILED = 'DELETE_ARTICLE_FAILED';
